### ISSUE TITLE
"Empty Slots" field for StadtRAD Hamburg is always 'null'

### ISSUE THREAD

**Issue by felixhaass** [eskerda/pybikes#125] opened 2016-04-06 13:40 UTC
Hi guys,

I'm playing around with the data for the StadtRAD service Hamburg. Thanks for the API and such great data!

Just a quick comment: it seems that the API returns for every station from the `stadtrad` network ID, a `null` value for the `empty_slots` field. Is that because StadtRAD Hamburg is not providing this information or just due to some glitch in the data?

Best,
Felix

**Comment by felixhaass** [comment] 2016-04-12 15:59
Ok, so I did some digging and it turns out that the Call-a-Bike API or the [JSON file returned by Call-a-Bike](https://www.callabike-interaktiv.de/kundenbuchung/hal2ajax_process.php?callee=getMarker&mapstadt_id=75&requester=bikesuche&ajxmod=hal2map&bereich=2&buchungsanfrage=N&webfirma_id=500&searchmode=default) does not include the information on the number of bike slots for a station. Only the free bikes are recorded. 

This is the same for *all* Call-a-Bike queries, since none of their stations apparently has electronic information stored. 

Unless someone has a workaround for this (I've searched for another source on the capacity of bike stations), this issue can be closed, I guess.

**Comment by eskerda** [comment] 2016-04-14 15:35
Still checking if something can be done. Do not close the issue yet!

**Comment by njoylab** [comment] 2016-04-14 15:39
Hi,
I don't think it's an issue. Those systems don't have the information because they don't have fixed racks. You can leave the bike locked inside a gps area.
Virtually you have infinite slots.

**Comment by eskerda** [comment] 2016-04-14 15:43
The problem is our definition of `empty_slots` as null, since this is a field we assume should be there (to not break apps). For some networks we do provide an indicator that slot information is not there with a `-1`.

Should think about the most obvious way to represent that on the API without creating yet another field.

**Comment by eskerda** [comment] 2017-06-22 19:27
Call a bike feeds are broken now, which makes this issue moot.

**Closed by eskerda** 2017-06-22 19:27 UTC

**Comment by erAck** [comment] 2018-10-27 21:05
> Those systems don't have the information because they don't have fixed racks. You can leave the bike locked inside a gps area.

That btw is only true for some cities, while in other cities there are fixed racks. For example Hamburg (where it's called StadtRAD but still is operated by Call-a-Bike). Though you can lock the bike beside the racks if all slots are taken.
